# おまじない
# @rules_cc//cc:defs.blz がラベル
load("@rules_cc//cc:defs.bzl", "cc_binary")

# cc_binaryのルールを記述
# cc_binary ruleからhello-world targetを作成
cc_binary(
    name = "hello-world",  # ターゲット
    srcs = ["hello-world.cc"],
)
