name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Cache bazel
        uses: actions/checkout@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{runner.os}}-${{env.cache-name}}

      - uses: actions/checkout@v3
      - name: Build the code
        run: bazel build //...
        